package com.jigong.app_attendance.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jigong.app_attendance.bean.AttendanceInfo;
import com.jigong.app_attendance.bean.WorkerInfo;

import com.jigong.app_attendance.greendao.AttendanceInfoDao;
import com.jigong.app_attendance.greendao.WorkerInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig attendanceInfoDaoConfig;
    private final DaoConfig workerInfoDaoConfig;

    private final AttendanceInfoDao attendanceInfoDao;
    private final WorkerInfoDao workerInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        attendanceInfoDaoConfig = daoConfigMap.get(AttendanceInfoDao.class).clone();
        attendanceInfoDaoConfig.initIdentityScope(type);

        workerInfoDaoConfig = daoConfigMap.get(WorkerInfoDao.class).clone();
        workerInfoDaoConfig.initIdentityScope(type);

        attendanceInfoDao = new AttendanceInfoDao(attendanceInfoDaoConfig, this);
        workerInfoDao = new WorkerInfoDao(workerInfoDaoConfig, this);

        registerDao(AttendanceInfo.class, attendanceInfoDao);
        registerDao(WorkerInfo.class, workerInfoDao);
    }
    
    public void clear() {
        attendanceInfoDaoConfig.clearIdentityScope();
        workerInfoDaoConfig.clearIdentityScope();
    }

    public AttendanceInfoDao getAttendanceInfoDao() {
        return attendanceInfoDao;
    }

    public WorkerInfoDao getWorkerInfoDao() {
        return workerInfoDao;
    }

}
