package com.jigong.app_attendance.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.jigong.app_attendance.bean.WorkerInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "WORKER_INFO".
*/
public class WorkerInfoDao extends AbstractDao<WorkerInfo, Long> {

    public static final String TABLENAME = "WORKER_INFO";

    /**
     * Properties of entity WorkerInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CustomId = new Property(1, String.class, "customId", false, "CUSTOM_ID");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property PersonType = new Property(3, String.class, "personType", false, "PERSON_TYPE");
        public final static Property Gender = new Property(4, String.class, "gender", false, "GENDER");
        public final static Property IdCard = new Property(5, String.class, "idCard", false, "ID_CARD");
        public final static Property CardType = new Property(6, String.class, "cardType", false, "CARD_TYPE");
        public final static Property Birthday = new Property(7, String.class, "birthday", false, "BIRTHDAY");
        public final static Property PicURI = new Property(8, String.class, "picURI", false, "PIC_URI");
    }


    public WorkerInfoDao(DaoConfig config) {
        super(config);
    }
    
    public WorkerInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"WORKER_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"CUSTOM_ID\" TEXT," + // 1: customId
                "\"NAME\" TEXT," + // 2: name
                "\"PERSON_TYPE\" TEXT," + // 3: personType
                "\"GENDER\" TEXT," + // 4: gender
                "\"ID_CARD\" TEXT," + // 5: idCard
                "\"CARD_TYPE\" TEXT," + // 6: cardType
                "\"BIRTHDAY\" TEXT," + // 7: birthday
                "\"PIC_URI\" TEXT);"); // 8: picURI
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"WORKER_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, WorkerInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String customId = entity.getCustomId();
        if (customId != null) {
            stmt.bindString(2, customId);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String personType = entity.getPersonType();
        if (personType != null) {
            stmt.bindString(4, personType);
        }
 
        String gender = entity.getGender();
        if (gender != null) {
            stmt.bindString(5, gender);
        }
 
        String idCard = entity.getIdCard();
        if (idCard != null) {
            stmt.bindString(6, idCard);
        }
 
        String cardType = entity.getCardType();
        if (cardType != null) {
            stmt.bindString(7, cardType);
        }
 
        String birthday = entity.getBirthday();
        if (birthday != null) {
            stmt.bindString(8, birthday);
        }
 
        String picURI = entity.getPicURI();
        if (picURI != null) {
            stmt.bindString(9, picURI);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, WorkerInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String customId = entity.getCustomId();
        if (customId != null) {
            stmt.bindString(2, customId);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String personType = entity.getPersonType();
        if (personType != null) {
            stmt.bindString(4, personType);
        }
 
        String gender = entity.getGender();
        if (gender != null) {
            stmt.bindString(5, gender);
        }
 
        String idCard = entity.getIdCard();
        if (idCard != null) {
            stmt.bindString(6, idCard);
        }
 
        String cardType = entity.getCardType();
        if (cardType != null) {
            stmt.bindString(7, cardType);
        }
 
        String birthday = entity.getBirthday();
        if (birthday != null) {
            stmt.bindString(8, birthday);
        }
 
        String picURI = entity.getPicURI();
        if (picURI != null) {
            stmt.bindString(9, picURI);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public WorkerInfo readEntity(Cursor cursor, int offset) {
        WorkerInfo entity = new WorkerInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // customId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // personType
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // gender
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // idCard
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // cardType
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // birthday
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8) // picURI
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, WorkerInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCustomId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPersonType(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setGender(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setIdCard(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setCardType(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setBirthday(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setPicURI(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(WorkerInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(WorkerInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(WorkerInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
